[#74] Added clinic attribute to Room and RoomSchedule
Exception: RoomScheduleService will be updated after the timeslotIterator branch is merged to prevent merge conflicts when trying to merge addClinic branch to master